services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_started
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=messenger_db
  rabbitmq:
    hostname: rabbitmq
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    restart: always
    ports:
      - "61613:61613"
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=RMQAdmin
      - RABBITMQ_DEFAULT_PASS=RMQPassword
      - HOSTNAME=rabbitmq
      - NODENAME=rabbitmq@rabbitmq
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"