version: '3.3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbit
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=messenger_db
  rabbit:
    image: rabbitmq:3.12.4-management
    hostname: rabbitmq
    command: rabbitmq-plugins enable rabbitmq_web_stomp
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=RMQAdmin
      - RABBITMQ_DEFAULT_PASS=RMQPassword