spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/messenger_db
    username: admin
    password: admin
  liquibase:
    change-log: classpath:migrations/changelog-master.xml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/messenger_db
    user: admin
    password: admin
  mail:
    host: smtp.gmail.com
    username: spring.email.sender.daemon@gmail.com
    password: dcwnxeciuqiyzvam
    protocol: smtp
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
jwt:
  secret: -=very=top=secret=key=for=messenger=app=to=jwt=secret=property=-
  expiration_time: 18000000